// Generated by scripts/extract-legal.py from the one.com snapshot in content/.
// Do not edit by hand; re-run the script instead.

export type LegalBlock = {
  type: "h2" | "h3" | "p" | "li" | "link";
  text: string;
  href?: string;
};

export const legalContent = {
  "imprint": {
    "de": [
      {
        "type": "p",
        "text": "Anschrift:\nAutak e.V.\nOttostr. 51A\n52070 Aachen"
      },
      {
        "type": "p",
        "text": "Vorstand:\nVorsitzende: Manuel Wessely\nStellv. Vorsitzende: Niklas Degener"
      },
      {
        "type": "p",
        "text": "Kassenführer: Jan Schauf\nSchriftführer: Florian Ernst"
      },
      {
        "type": "p",
        "text": "Registereintrag\nEingetragen im Vereinsregister.\nRegistergericht: Amtsgericht Aachen"
      },
      {
        "type": "p",
        "text": "Das Impressum gilt für\nautak.org"
      },
      {
        "type": "h3",
        "text": "Download"
      },
      {
        "type": "link",
        "text": "Vereinfachter Zuwendungsnachweis",
        "href": "/onewebmedia/Vereinfachter-Zuwendungsnachweis.pdf"
      },
      {
        "type": "h3",
        "text": "Disclaimer"
      },
      {
        "type": "h3",
        "text": "§ 1 Warnhinweis zu Inhalten"
      },
      {
        "type": "p",
        "text": "Die kostenlosen und frei zugänglichen Inhalte dieser Webseite wurden mit größtmöglicher Sorgfalt erstellt. Der Anbieter dieser Webseite übernimmt jedoch keine Gewähr für die Richtigkeit und Aktualität der bereitgestellten kostenlosen und frei zugänglichen journalistischen Ratgeber und Nachrichten. Namentlich gekennzeichnete Beiträge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder. Allein durch den Aufruf der kostenlosen und frei zugänglichen Inhalte kommt keinerlei Vertragsverhältnis zwischen dem Nutzer und dem Anbieter zustande, insoweit fehlt es am Rechtsbindungswillen des Anbieters."
      },
      {
        "type": "h3",
        "text": "§ 2 Externe Links"
      },
      {
        "type": "p",
        "text": "Diese Website enthält Verknüpfungen zu Websites Dritter (“externe Links”). Diese Websites unterliegen der Haftung der jeweiligen Betreiber. Der Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. Zu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. Der Anbieter hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. Das Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. Eine ständige Kontrolle der externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. Bei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht."
      },
      {
        "type": "h3",
        "text": "§ 3 Urheber- und Leistungsschutzrechte"
      },
      {
        "type": "p",
        "text": "Die auf dieser Website veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. Dies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. Inhalte und Rechte Dritter sind dabei als solche gekennzeichnet. Die unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. Lediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt."
      },
      {
        "type": "p",
        "text": "Die Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zulässig."
      },
      {
        "type": "h3",
        "text": "§ 4 Besondere Nutzungsbedingungen"
      },
      {
        "type": "p",
        "text": "Soweit besondere Bedingungen für einzelne Nutzungen dieser Website von den vorgenannten Paragraphen abweichen, wird an entsprechender Stelle ausdrücklich darauf hingewiesen. In diesem Falle gelten im jeweiligen Einzelfall die besonderen Nutzungsbedingungen."
      },
      {
        "type": "p",
        "text": "Quelle des Disclaimers: Impressum Vorlage von JuraForum.de"
      }
    ],
    "en": [
      {
        "type": "p",
        "text": "Address:"
      },
      {
        "type": "p",
        "text": "Autak e.V.\nOttostr. 51A\n52070 Aachen"
      },
      {
        "type": "p",
        "text": "Board of Directors:"
      },
      {
        "type": "p",
        "text": "Chairwoman: Manuel Wessely"
      },
      {
        "type": "p",
        "text": "Vice-Chairman: Niklas Degener"
      },
      {
        "type": "p",
        "text": "Treasurer: Patricia Fritze\nClerk: Gernot Sümmermann"
      },
      {
        "type": "p",
        "text": "1st assessor: Florian Ernst"
      },
      {
        "type": "p",
        "text": "Register entry\nRegistered in the register of associations.\nRegister court: Local court Aachen"
      },
      {
        "type": "p",
        "text": "The imprint is valid for\nautak.org"
      },
      {
        "type": "h3",
        "text": "Download"
      },
      {
        "type": "link",
        "text": "Simplified proof of funding",
        "href": "/onewebmedia/Vereinfachter-Zuwendungsnachweis.pdf"
      },
      {
        "type": "h3",
        "text": "Disclaimer"
      },
      {
        "type": "h3",
        "text": "§ 1 Content warning"
      },
      {
        "type": "p",
        "text": "The free and freely accessible contents of this website have been created with the greatest possible care. However, the provider of this website does not guarantee the accuracy and timeliness of the provided free and freely accessible journalistic guides and news. Contributions identified by name reflect the opinion of the respective author and not always the opinion of the provider. Simply by calling up the free and freely accessible content, no contractual relationship is established between the user and the provider; in this respect, the provider's intention to be legally bound is lacking."
      },
      {
        "type": "h3",
        "text": "§ 2 External links"
      },
      {
        "type": "p",
        "text": "This website contains links to third-party websites (\"external links\"). These websites are subject to the liability of the respective operators. When the external links were first created, the provider checked the external content for any legal violations. At that time, no legal violations were apparent. The provider has no influence on the current and future design and content of the linked pages. The inclusion of external links does not imply that the provider adopts the content behind the reference or link as its own. It is not reasonable for the provider to constantly monitor the external links without concrete evidence of legal violations. However, such external links will be deleted immediately if legal violations become known."
      },
      {
        "type": "h3",
        "text": "§ 3 Copyrights and ancillary copyrights"
      },
      {
        "type": "p",
        "text": "The contents published on this website are subject to German copyright and ancillary copyright law. Any use not permitted by German copyright and ancillary copyright law requires the prior written consent of the provider or the respective rights holder. This applies in particular to the copying, editing, translation, storage, processing or reproduction of content in databases or other electronic media and systems. Contents and rights of third parties are marked as such. The unauthorized reproduction or distribution of individual content or complete pages is not permitted and is punishable by law. Only the production of copies and downloads for personal, private and non-commercial use is permitted."
      },
      {
        "type": "p",
        "text": "The display of this website in external frames is only permitted with written permission."
      },
      {
        "type": "h3",
        "text": "§ 4 Special terms of use"
      },
      {
        "type": "p",
        "text": "Insofar as special conditions for individual uses of this website deviate from the aforementioned paragraphs, this will be expressly pointed out at the appropriate place. In this case, the special terms of use apply in the respective individual case."
      },
      {
        "type": "p",
        "text": "Source of the disclaimer: Imprint template from JuraForum.de"
      }
    ]
  },
  "statutes": {
    "de": [
      {
        "type": "h3",
        "text": "Name und Sitz des Vereins"
      },
      {
        "type": "p",
        "text": "Der Verein führt den Namen: Autak. Er soll in das Vereinsregister eingetragen werden und nach Eintragung den Rechtsformzusatz e.V. erhalten."
      },
      {
        "type": "h3",
        "text": "Sitz des Vereins ist Aachen"
      },
      {
        "type": "h3",
        "text": "Geschäftsjahr"
      },
      {
        "type": "p",
        "text": "Das Geschäftsjahr ist das Kalenderjahr."
      },
      {
        "type": "h3",
        "text": "Zweck des Vereins"
      },
      {
        "type": "p",
        "text": "Der Verein verfolgt ausschließlich und unmittelbar gemeinnützige Zwecke im Sinne des Abschnitts “Steuerbegünstigte Zwecke” der Abgabenordnung."
      },
      {
        "type": "p",
        "text": "Zweck des Vereins ist:a. die Förderung von Wissenschaft und Forschung;b. die Förderung des bürgerschaftlichen Engagements zugunsten gemeinnütziger und mildtätiger Zwecke;c. die Förderung des öffentlichen Gesundheitswesens und der öffentlichen Gesundheitspflege;d. die Förderung der Erziehung, Volks- und Berufsbildung einschließlich der Studentenhilfe."
      },
      {
        "type": "p",
        "text": "Der Satzungszweck wird verwirklicht insbesondere durch:a. Awarenessprojekte;b. Entwicklung von Software und Hardware;c. Wissenschaftliche Veranstaltungen, Forschungsvorhaben und Vergabe von Forschungsaufträgen."
      },
      {
        "type": "h3",
        "text": "Gemeinnützigkeit"
      },
      {
        "type": "p",
        "text": "Der Verein ist selbstlos tätig; er verfolgt nicht in erster Linie eigenwirtschaftliche Zwecke."
      },
      {
        "type": "p",
        "text": "Mittel des Vereins dürfen nur für die satzungsmäßigen Zwecke verwendet werden. Die Mitglieder erhalten in ihrer Eigenschaft als Mitglieder keine Zuwendungen aus Mitteln des Vereins."
      },
      {
        "type": "p",
        "text": "Es darf keine Person durch Ausgaben, die dem Zweck der Körperschaft fremd sind, oder durch unverhältnismäßig hohe Vergütungen begünstigt werden."
      },
      {
        "type": "h3",
        "text": "Mitgliedschaft"
      },
      {
        "type": "p",
        "text": "Jede Person, die die Zwecke des Vereins zu fördern bereit ist, kann Mitglied werden. Bei Minderjährigen ist der Aufnahmeantrag durch die gesetzlichen Vertreter:innen zu stellen."
      },
      {
        "type": "p",
        "text": "Die Aufnahme eines Mitgliedes erfolgt auf schriftlichen Antrag durch den Vorstand oder durch die Mitgliederversammlung."
      },
      {
        "type": "p",
        "text": "Der Austritt eines Mitgliedes kann mit einer Frist von 4 Wochen gegenüber dem Vorstand schriftlich erklärt werden."
      },
      {
        "type": "p",
        "text": "Mitglieder des Vereins, die ihren Verpflichtungen nicht nachkommen oder in sonstiger Weise gegen die Interessen des Vereins verstoßen, können vom Vorstand ausgeschlossen werden. Gegen den Ausschluss kann schriftlich innerhalb von 2 Wochen unter Angabe von Gründen Berufung eingelegt werden. Der Vorstand hat dann diese Berufung der Mitgliederversammlung zur endgültigen Entscheidung vorzulegen."
      },
      {
        "type": "p",
        "text": "Bei Beendigung der Mitgliedschaft erlöschen alle Ansprüche aus dem Mitgliedschaftsverhältnis. Eine Rückgewähr von Beiträgen oder Spenden ist ausgeschlossen."
      },
      {
        "type": "p",
        "text": "Ein Stimmrecht haben nur aktive Mitglieder. Eine Übertragung des Stimmrechts auf andere stimmberechtigte Mitglieder ist möglich und bedarf der (digitalen) Schriftform."
      },
      {
        "type": "h3",
        "text": "Mitgliedsbeiträge"
      },
      {
        "type": "p",
        "text": "Von den Mitgliedern werden jedes Semester Beiträge erhoben. Die Höhe des jeweiligen Mitgliedsbeitrags wird durch die Beitragsordnung festgesetzt."
      },
      {
        "type": "h3",
        "text": "Organe"
      },
      {
        "type": "p",
        "text": "Organe des Vereins sind der Vorstand und die Mitgliederversammlung."
      },
      {
        "type": "h3",
        "text": "Vorstand"
      },
      {
        "type": "p",
        "text": "Den Vorstand bilden:a. der:die Vorsitzende und dessen:deren Stellvertretungb. der:die Kassenführer:inc. der:die Schriftführer:ind. bis zu drei Beisitzer:innen"
      },
      {
        "type": "p",
        "text": "Außergerichtlich und gerichtlich wird der Verein durch den:die Vorsitzende:n oder die Stellvertretung einzeln vertreten. Diese sind ebenfalls befugt jeweils Vorstandsmitglieder in bestimmten Bereichen Einzelvertretungsbefugnis zu erteilen."
      },
      {
        "type": "p",
        "text": "Die Wahl erfolgt in der oben genannten Reihenfolge."
      },
      {
        "type": "p",
        "text": "Für den Vorstand gilt eine Geschlechterquote von maximal 70%. Kandidat:innen sind nur gewählt, soweit diese Quote erfüllt wird. Wird die Quote nicht erfüllt, so sind im ersten Wahlgang die Kandidat:innen des überrepräsentierten Geschlechts nur bis zu ihrer Höchstquote von 70% gewählt. Die Kandidat:innen der unterrepräsentierten Geschlechter sind nur gewählt, soweit sie mindestens die gleiche Stimmenzahl erreichen wie der oder die erste Nichtgewählte der überrepräsentierten Gruppe. Zur Einhaltung dieser Regelung können Positionen unbesetzt bleiben und können jederzeit durch eine Mitgliederversammlung nachgewählt werden."
      },
      {
        "type": "p",
        "text": "Der Vorstand wird von der Mitgliederversammlung für die Dauer von 1 Jahr gewählt. Er bleibt über die vorgenannte Amtszeit hinaus bis zur Wahl eines neuen Vorstandes im Amt. Wiederwahl ist möglich."
      },
      {
        "type": "p",
        "text": "Scheidet ein Vorstandsmitglied vorzeitig aus dem Vorstand aus, so ist der Restvorstand befugt die Aufgaben und die Verantwortlichkeiten auf den Restvorstand zu verteilen."
      },
      {
        "type": "p",
        "text": "Satzungsänderungen, die von Behörden oder Gerichten angeregt oder verlangt werden, kann der Vorstand von sich aus beschließen."
      },
      {
        "type": "h3",
        "text": "Mitgliederversammlung"
      },
      {
        "type": "p",
        "text": "Die Mitgliederversammlung ist einmal jährlich einzuberufen."
      },
      {
        "type": "p",
        "text": "Außerordentliche Mitgliederversammlungen sind einzuberufen, wenn das Interesse des Vereins es erfordert oder wenn 20% Prozent der Mitglieder die Einberufung schriftlich unter Angabe von Gründen vom Vorstand verlangen."
      },
      {
        "type": "p",
        "text": "Die Einberufung der Mitgliederversammlung erfolgt durch den:die Vorsitzende:n, bei dessen Verhinderung durch dessen:deren Stellvertretung, schriftlich oder per E-Mail unter Einhaltung einer Einladungsfrist von 2 Wochen. Dabei sind die vom Vorstand beschlossenen Tagesordnungspunkte anzugeben."
      },
      {
        "type": "p",
        "text": "Jede ordnungsgemäß eingeladene Mitgliederversammlung ist ohne Rücksicht auf die Anzahl der erschienenen Mitglieder beschlussfähig."
      },
      {
        "type": "p",
        "text": "Die Mitgliederversammlung fasst ihre Beschlüsse mit der Mehrheit der abgegebenen gültigen Stimmen."
      },
      {
        "type": "p",
        "text": "Für Satzungsänderungen ist eine Mehrheit von 2/3 der abgegebenen Stimmen erforderlich."
      },
      {
        "type": "p",
        "text": "Die Mitgliederversammlung inkl. der Wahlen kann in digitaler Form stattfinden."
      },
      {
        "type": "h3",
        "text": "Beurkundung der Beschlüsse"
      },
      {
        "type": "p",
        "text": "Über die in den Vorstandssitzungen und Mitgliederversammlungen gefassten Beschlüsse ist ein Protokoll anzufertigen. Dieses ist von dem:der Versammlungsleiter:in und von dem:der Protokollführer:in, die jeweils durch eine einfache Mehrheit in der Mitgliederversammlung bestimmt werden, zu unterzeichnen."
      },
      {
        "type": "h3",
        "text": "Patente"
      },
      {
        "type": "p",
        "text": "Gehen aus der Vereinsarbeit Patentanmeldungen hervor, entfallen die Rechte auf den Verein. Daraus entstehende Einkünfte dürfen nur für satzungskonforme Zwecke verwendet werden."
      },
      {
        "type": "h3",
        "text": "Datenschutz"
      },
      {
        "type": "p",
        "text": "Näheres regelt die Datenschutzerklärung."
      },
      {
        "type": "h3",
        "text": "Kassenprüfung"
      },
      {
        "type": "p",
        "text": "Die Mitgliederversammlung wählt für die Dauer von einem Jahr zwei Kassenprüfer:innen."
      },
      {
        "type": "p",
        "text": "Diese dürfen nicht Mitglied des Vorstands sein."
      },
      {
        "type": "p",
        "text": "Wiederwahl ist zulässig."
      },
      {
        "type": "p",
        "text": "Soll der Vorstand entlastet werden, ist der Mitgliederversammlung eine Woche vor deren Zusammentreten ein Kassenprüfbericht vorzulegen."
      },
      {
        "type": "h3",
        "text": "Auflösung des Vereins"
      },
      {
        "type": "p",
        "text": "Bei Auflösung des Vereins ist eine außerordentliche Mitgliederversammlung einzuberufen. Diese Mitgliederversammlung darf als einzigen Tagesordnungspunkt nur die Auflösung des Vereins und die hiermit zusammenhängenden Beschlüsse zum Gegenstand haben. Für die Auflösung ist eine 3/4-Mehrheit der abgegebenen gültigen Stimmen erforderlich."
      },
      {
        "type": "p",
        "text": "Bei Auflösung des Vereins oder bei Wegfall steuerbegünstigter Zwecke fällt das Vermögen des Vereins:a. an den TechAachen e.V. (Templergraben 55, 52062 Aachen; Steuernummer 201/5917/4188 bzw. 201/5903/5578), der es unmittelbar und ausschließlich für gemeinnützige Zwecke zu verwenden hat;b. an eine juristische Person des öffentlichen Rechts oder eine andere steuerbegünstigte Körperschaft zwecks Verwendung für einen gemeinnützigen Zweck, z.B. Förderung von Wissenschaft und Forschung, Erziehung, Volks- und Berufsbildung, der Unterstützung von Personen, die im Sinne von § 53 AO bedürftig sind."
      },
      {
        "type": "h3",
        "text": "Ehrenamtspauschale"
      },
      {
        "type": "p",
        "text": "Der Vorstand ist ehrenamtlich tätig. Die Mitgliederversammlung kann aber beschließen, dass der Vorstand ausgenommen Beisitzer:innen für seinen Zeitaufwand eine angemessene Vergütung erhält, deren Höhe von der Mitgliederversammlung bestimmt wird."
      },
      {
        "type": "h3",
        "text": "Sonstiges"
      },
      {
        "type": "p",
        "text": "Soweit in dieser Satzung keine besonderen Regelungen getroffen wurden, kommen die §§ 21 bis 79 BGB zur Anwendung."
      },
      {
        "type": "p",
        "text": "Die Satzung wurde am 05.05.2021 errichtet und mit Änderungsbeschluss am 05.10.2023 geändert."
      }
    ],
    "en": [
      {
        "type": "li",
        "text": "1 Name and seat of the association"
      },
      {
        "type": "p",
        "text": "(1) The name of the association is: Autak"
      },
      {
        "type": "p",
        "text": "It shall be entered in the register of associations and after registration shall receive the legal form suffix e.V.."
      },
      {
        "type": "p",
        "text": "(2) The registered office of the Association is Aachen."
      },
      {
        "type": "li",
        "text": "2 Fiscal Year"
      },
      {
        "type": "p",
        "text": "The business year is the calendar year."
      },
      {
        "type": "li",
        "text": "3 Purpose of the Association"
      },
      {
        "type": "p",
        "text": "The Association exclusively and directly pursues charitable purposes within the meaning of the section \"Tax-privileged purposes\" of the German Tax Code."
      },
      {
        "type": "h3",
        "text": "The purpose of the association is"
      },
      {
        "type": "h3",
        "text": "the promotion of science and research"
      },
      {
        "type": "p",
        "text": "the promotion of civic engagement for the benefit of charitable and benevolent purposes;"
      },
      {
        "type": "h3",
        "text": "the promotion of public health and public health care;"
      },
      {
        "type": "p",
        "text": "the promotion of education, popular education and vocational training, including student aid."
      },
      {
        "type": "h3",
        "text": "The purpose of the statutes is realized in particular through"
      },
      {
        "type": "h3",
        "text": "Awareness projects;;"
      },
      {
        "type": "h3",
        "text": "Development of software and hardware;"
      },
      {
        "type": "p",
        "text": "Scientific events, research projects and the awarding of research contracts."
      },
      {
        "type": "li",
        "text": "4 Non-profit status"
      },
      {
        "type": "p",
        "text": "The association is selflessly active; it does not primarily pursue its own economic purposes."
      },
      {
        "type": "p",
        "text": "Funds of the Association may only be used for the purposes set forth in the Articles of Association. In their capacity as members, the members shall not receive any benefits from the Association's funds."
      },
      {
        "type": "p",
        "text": "No person may benefit from expenditures that are alien to the purpose of the corporation or from disproportionately high remuneration."
      },
      {
        "type": "li",
        "text": "5 Membership"
      },
      {
        "type": "p",
        "text": "Any person who is willing to promote the purposes of the Association may become a member. In the case of minors, the application for membership must be submitted by their legal representatives."
      },
      {
        "type": "p",
        "text": "The admission of a member takes place on written application by the executive committee or by the meeting of the members."
      },
      {
        "type": "p",
        "text": "The resignation of a member can be declared in writing to the board with a notice period of 4 weeks."
      },
      {
        "type": "p",
        "text": "Members of the association who do not fulfill their obligations or otherwise violate the interests of the association can be excluded by the board. An appeal against the exclusion can be made in writing within 2 weeks, stating the reasons. The board must then submit this appeal to the general meeting for a final decision."
      },
      {
        "type": "p",
        "text": "Upon termination of membership, all claims arising from the membership relationship shall expire. A refund of contributions or donations is excluded."
      },
      {
        "type": "p",
        "text": "Only active members have a right to vote. Transfer of voting rights to other members with voting rights is possible and requires the (digital) written form."
      },
      {
        "type": "li",
        "text": "6 Membership fees"
      },
      {
        "type": "p",
        "text": "Dues are levied from the members every semester. The amount of the respective membership fee is determined by the fee regulations."
      },
      {
        "type": "li",
        "text": "7 Organs"
      },
      {
        "type": "p",
        "text": "The organs of the association are the board of directors and the general meeting."
      },
      {
        "type": "li",
        "text": "8 Board of Directors"
      },
      {
        "type": "h3",
        "text": "The Board of Directors consists of"
      },
      {
        "type": "h3",
        "text": "the chairperson and his/her deputy"
      },
      {
        "type": "h3",
        "text": "the treasurer"
      },
      {
        "type": "li",
        "text": "the clerk"
      },
      {
        "type": "h3",
        "text": "up to three assessors"
      },
      {
        "type": "p",
        "text": "The chairperson and the deputy chairperson are authorized to represent the association independently. They are also authorized to grant individual power of representation to members of the Board of Directors in certain areas."
      },
      {
        "type": "p",
        "text": "The election shall be held in the above order."
      },
      {
        "type": "p",
        "text": "A maximum gender quota of 70% applies to the Executive Board. Candidates are only elected if this quota is met. If the quota is not met, the candidates of the overrepresented gender are elected in the first ballot only up to their maximum quota of 70%. The candidates of the underrepresented gender are only elected insofar as they achieve at least the same number of votes as the first non-elected candidate of the overrepresented group. In order to comply with this rule, positions may remain unfilled and can be re-elected at any time by a general meeting."
      },
      {
        "type": "p",
        "text": "The board of directors is elected by the general meeting for a period of 1 year. It remains in office beyond the aforementioned term until the election of a new board. Re-election is possible."
      },
      {
        "type": "p",
        "text": "If a board member leaves the board prematurely, the remaining board is authorized to distribute the tasks and responsibilities to the remaining board."
      },
      {
        "type": "p",
        "text": "Amendments to the Articles of Association that are suggested or demanded by authorities or courts may be decided by the Executive Board on its own initiative."
      },
      {
        "type": "li",
        "text": "9 General meeting"
      },
      {
        "type": "p",
        "text": "The general meeting is to be convened once a year."
      },
      {
        "type": "p",
        "text": "Extraordinary General Meetings shall be convened if the interest of the Association requires it or if 20% percent of the members request the convening in writing from the Executive Board, stating the reasons."
      },
      {
        "type": "p",
        "text": "The general meeting shall be convened by the chairperson or, if the chairperson is prevented from doing so, by the deputy chairperson in writing or by e-mail, observing a notice period of 2 weeks. The items on the agenda decided by the Executive Board must be stated."
      },
      {
        "type": "p",
        "text": "Any General Meeting duly convened shall constitute a quorum irrespective of the number of members present."
      },
      {
        "type": "p",
        "text": "The General Meeting shall adopt its resolutions by a majority of the valid votes cast."
      },
      {
        "type": "p",
        "text": "A majority of 2/3 of the votes cast is required for amendments to the Articles of Association."
      },
      {
        "type": "p",
        "text": "The general meeting including the elections can take place in digital form."
      },
      {
        "type": "li",
        "text": "10 Certification of the resolutions"
      },
      {
        "type": "p",
        "text": "Minutes are to be taken of the resolutions passed at the board meetings and general meetings. The minutes shall be signed by the chairperson of the meeting and the keeper of the minutes, each of whom shall be appointed by a simple majority at the general meeting."
      },
      {
        "type": "li",
        "text": "11 Patents"
      },
      {
        "type": "p",
        "text": "If patent applications result from the work of the association, the rights shall pass to the association. Any income arising therefrom may only be used for purposes in accordance with the Articles of Association."
      },
      {
        "type": "li",
        "text": "12 Privacy"
      },
      {
        "type": "p",
        "text": "Further details are regulated in the privacy policy."
      },
      {
        "type": "li",
        "text": "13 Cash audit"
      },
      {
        "type": "p",
        "text": "The general meeting elects two auditors for a period of one year."
      },
      {
        "type": "p",
        "text": "These may not be members of the Board of Management."
      },
      {
        "type": "p",
        "text": "Re-election is permitted."
      },
      {
        "type": "p",
        "text": "If the Board is to be discharged, a cash audit report must be submitted to the General Meeting one week before it convenes."
      },
      {
        "type": "h3",
        "text": "14 Dissolution of the association"
      },
      {
        "type": "p",
        "text": "In the event of dissolution of the Association, an extraordinary General Meeting shall be convened. The only item on the agenda of this general meeting may be the dissolution of the association and the related resolutions. A 3/4 majority of the valid votes cast is required for dissolution."
      },
      {
        "type": "p",
        "text": "In the event of the dissolution of the Association or in the event of the discontinuation of tax-privileged purposes, the assets of the Association shall fall to"
      },
      {
        "type": "p",
        "text": "to TechAachen e.V. (Templergraben 55, 52062 Aachen; tax number 201/5917/4188 or 201/5903/5578), which must use it directly and exclusively for charitable purposes;"
      },
      {
        "type": "p",
        "text": "to a legal entity under public law or another tax-privileged corporation for use for a charitable purpose, e.g. the promotion of science and research, education, popular and vocational training, the support of persons who are in need within the meaning of § 53 AO due to need."
      },
      {
        "type": "h3",
        "text": "15 Other"
      },
      {
        "type": "p",
        "text": "Insofar as no special provisions have been made in these Articles of Association, sections 21 to 79 of the German Civil Code apply."
      },
      {
        "type": "p",
        "text": "The Articles of Association were established on 05.05.2021."
      }
    ]
  },
  "contributions": {
    "de": [
      {
        "type": "p",
        "text": "Auf der Grundlage des § 9 Ziff.4 der Satzung vom Autak e.V. hat die Mitgliederversammlung in ihrer Sitzung am 05.05.2021 in Aachen die nachfolgende Beitragsordnung beschlossen. Die Höhe des Mitgliedsbeitrags richtet sich nach der Art der Mitgliedschaft. Der Beitrag wird jedes Semester am 01.04. bzw. 1.10. fällig. Bei Aufnahme als zahlendes Mitglied wird der Mitgliedsbeitrag sofort und in voller Höhe fällig."
      },
      {
        "type": "li",
        "text": "1 Grundsatz"
      },
      {
        "type": "p",
        "text": "Diese Beitragsordnung ist nicht Bestandteil der Satzung. Sie regelt die Beitragsverpflichtungen der Mitglieder sowie die Gebühren und Umlagen. Sie kann nur von der Mitgliederversammlung des Vereins geändert werden."
      },
      {
        "type": "p",
        "text": "Bei Erhöhung der Beiträge haben zahlende Mitglieder die Möglichkeit zur unmittelbaren Kündigung."
      },
      {
        "type": "li",
        "text": "2 Beiträge"
      },
      {
        "type": "li",
        "text": "3 Zusätzliches"
      },
      {
        "type": "li",
        "text": "Der Vorstand ist ermächtigt, Beiträge auf Antrag zu stunden, zu ermäßigen oder zu erlassen. Ein Rechtsanspruch auf Ratenzahlung und / oder Stundung der Beitragsschuld besteht nicht."
      },
      {
        "type": "li",
        "text": "Für die Beitragshöhe ist der am Fälligkeitstag bestehende Mitgliederstatus maßgebend."
      },
      {
        "type": "li",
        "text": "Nur aktive Mitglieder können Ämter im Verein übernehmen."
      }
    ],
    "en": [
      {
        "type": "p",
        "text": "On the basis of § 9 No. 4 of the Statutes of Autak e.V., the General Assembly decided on the following membership fee regulations at its meeting on 05.05.2021 in Aachen. The amount of the membership fee depends on the type of membership. The membership fee is due every semester on 01.04. and 1.10. respectively. Upon acceptance as a paying member, the membership fee is due immediately and in full."
      },
      {
        "type": "li",
        "text": "1 Principle"
      },
      {
        "type": "p",
        "text": "These contribution regulations are not part of the Articles of Association. They regulate the contribution obligations of the members as well as the fees and apportionments. It can only be changed by the general meeting of the association."
      },
      {
        "type": "p",
        "text": "In the event of an increase in contributions, paying members have the option of immediate cancellation."
      },
      {
        "type": "li",
        "text": "2 Contributions"
      },
      {
        "type": "li",
        "text": "3 Additional"
      },
      {
        "type": "p",
        "text": "The Board of Directors is authorized to defer, reduce or waive dues upon request. There is no legal entitlement to payment by installments and / or deferral of the dues debt."
      },
      {
        "type": "p",
        "text": "The membership status existing on the due date shall be decisive for the amount of the contribution."
      },
      {
        "type": "p",
        "text": "Only active members can hold offices in the association."
      }
    ]
  },
  "privacy": {
    "de": [
      {
        "type": "h3",
        "text": "Allgemeine Hinweise"
      },
      {
        "type": "p",
        "text": "Wir freuen uns über Ihren Besuch auf unserer Website sowie über Ihr Interesse an unserem gemeinnützigen Verein Autak e.V. Wir nehmen den Schutz Ihrer Daten ernst und wir möchten, dass Sie sich beim Besuch unserer Internet-Seiten wohl fühlen. Der Schutz Ihrer Privatsphäre bei der Verarbeitung personenbezogener Daten ist für uns ein wichtiges Anliegen, welches wir stets berücksichtigen. Wir verarbeiten personenbezogene Daten, die beim Besuch unserer Webseiten erhoben werden gemäß den datenschutzrechtlichen Bestimmungen der europäischen Datenschutzgrundverordnung (DSGVO). Bitte lesen Sie diese Datenschutz- und Cookie-Richtlinien sorgfältig durch, bevor Sie diese Website nutzen. Sie können diesen Richtlinien entnehmen, wie wir mit Ihren Daten umgehen und Cookies einsetzen. Mit der Nutzung dieser Website akzeptieren Sie diese Regelungen. Unsere Webseiten können Links zu Webseiten anderer Anbieter enthalten, auf die sich diese Datenschutzerklärung nicht erstreckt."
      },
      {
        "type": "h3",
        "text": "Sicherheit"
      },
      {
        "type": "p",
        "text": "Wir setzen technische und organisatorische Sicherheitsmaßnahmen ein, um Ihre durch uns verwalteten Daten gegen Manipulationen, Verlust, Zerstörung und gegen den Zugriff unberechtigter Personen zu schützen. Unsere Sicherheitsmaßnahmen werden entsprechend der technologischen Entwicklung fortlaufend verbessert."
      },
      {
        "type": "h3",
        "text": "Auskunftsrecht, Sperrung und Löschung"
      },
      {
        "type": "p",
        "text": "Auf Anforderung teilen wir Ihnen unverzüglich schriftlich entsprechend des geltenden Rechts mit, ob und welche personenbezogenen Daten von Ihnen bei uns gespeichert sind. Sollten trotz unserer Bemühungen um Datenrichtigkeit und Aktualität falsche Informationen gespeichert sein, werden wir diese auf Ihre Aufforderung hin berichtigen. Sie haben außerdem das Recht, jederzeit Ihre persönlichen Daten sperren bzw. löschen zu lassen. Wenn Sie Fragen hinsichtlich der Verarbeitung Ihrer personenbezogenen Daten haben, können Sie sich an unseren Beauftragten für den Datenschutz wenden, der auch im Falle von Auskunftsersuchen, Anregungen oder Beschwerden zur Verfügung steht. Darüber hinaus haben Sie das Recht auf Beschwerde bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat ihres Aufenthaltsorts, ihres Arbeitsplatzes oder des Orts des mutmaßlichen Verstoßes, wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten rechtswidrig ist."
      },
      {
        "type": "h3",
        "text": "Verantwortliche Stelle"
      },
      {
        "type": "p",
        "text": "Verantwortliche Stelle i.S.d. DSGVO ist:"
      },
      {
        "type": "p",
        "text": "Autak e.V."
      },
      {
        "type": "h3",
        "text": "Ottostr. 51A"
      },
      {
        "type": "h3",
        "text": "52070 Aachen"
      },
      {
        "type": "h3",
        "text": "Zuständige Aufsichtsbehörde"
      },
      {
        "type": "p",
        "text": "Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen Postfach 20 04 44 40102 Düsseldorf Tel.: 0211/38424-0 Fax: 0211/38424-10 E-Mail: poststelle@ldi.nrw.de"
      },
      {
        "type": "h3",
        "text": "Erhebung, Verarbeitung und Speicherung persönlicher Daten"
      },
      {
        "type": "p",
        "text": "Wenn Sie unsere Webseiten besuchen, speichern unsere Webserver standardmäßig die IP-Adresse, die Ihnen von Ihrem Internet Service Provider zugewiesen wurde, die Webseite, von der aus Sie uns besuchen, die Webseiten, die Sie bei uns besuchen, den verwendeten Browsertyp und die Browserversion sowie das Datum und die Dauer des Besuches. Mit Ausnahme der IP- Adresse werden Personenbezogene Daten nur dann und nur für die ausdrücklich genannten Zwecke gespeichert, wenn Sie uns diese von sich aus, z.B. im Rahmen einer Registrierung, einer Umfrage, eines Preisausschreibens oder zur Durchführung eines Vertrages zur Verfügung stellen. Sofern nicht anders angegeben werden personenbezogene Daten nur so lange, wie dies zur Erfüllung der verfolgten Zwecke notwendig ist von uns gespeichert."
      },
      {
        "type": "h3",
        "text": "Nutzung, Weitergabe persönlicher Daten und Zweckbindung"
      },
      {
        "type": "p",
        "text": "Rechtsgrundlage der Datenverarbeitung in unserem Verein ist Art 6 Abs. 1, Buchstabe f DSGVO. Unsere Interessen an der Datenverarbeitung sind insbesondere die Sicherstellung des Betriebs unseres Vereins und die Sicherheit der Webseite, die Untersuchung der Art und Weise der Nutzung der Webseite durch Besucher, und die Vereinfachung der Nutzung der Webseite, sowie für Marketingzwecke im jeweils dafür erforderlichen Umfang. Insbesondere wenn Sie uns persönliche Daten zu dem Zweck übermitteln, Sie über unsere Produkte und Dienstleistungen zu informieren, möchten wir Ihre Daten dazu nutzen, Sie gegebenenfalls zu befragen. Selbstverständlich ist die Teilnahme an solchen Aktionen freiwillig. Falls Sie hiermit nicht einverstanden sind, können Sie uns dies jederzeit mitteilen, damit wir die Daten entsprechend sperren können. Personenbezogene Daten werden von uns grundsätzlich nicht ohne Ihre Einwilligung weitergegeben. Wenn und soweit wir Dritte im Rahmen der Erfüllung von Verträgen einschalten (etwa Logistik-Dienstleister) erhalten diese personenbezogenen Daten nur in dem Umfang, in welchem die Übermittlung für die entsprechende Leistung erforderlich ist. Für den Fall, dass wir bestimmte Teile der Datenverarbeitung auslagern („Auftragsverarbeitung“), verpflichten wir Auftragsverarbeiter vertraglich dazu, personenbezogene Daten nur im Einklang mit den Anforderungen der Datenschutzgesetze zu verwenden und den Schutz der Rechte der betroffenen Person zu gewährleisten. Übermittlungen personenbezogener Daten an staatliche Einrichtungen und Behörden erfolgen nur im Rahmen zwingender nationaler Rechtsvorschriften. Eine Datenübertragung an Stellen oder Personen außerhalb der EU außerhalb der in dieser Erklärung genannten Fälle findet nicht statt und ist nicht geplant. Wir behalten uns vor, Daten nachträglich zu prüfen, wenn konkrete Anhaltspunkte für eine rechtswidrige Nutzung bekannt werden oder es zur Erkennung und Beseitigung von Störungen erforderlich ist."
      }
    ],
    "en": [
      {
        "type": "h3",
        "text": "General information"
      },
      {
        "type": "p",
        "text": "Thank you for visiting our website and for your interest in our non-profit association Autak e.V. We take the protection of your data seriously and we want you to feel comfortable when visiting our internet pages. The protection of your privacy when processing personal data is an important concern for us, which we always take into account. We process personal data collected when you visit our websites in accordance with the data protection provisions of the European General Data Protection Regulation (DSGVO). Please read this privacy and cookie policy carefully before using this website. You can see from these guidelines how we handle your data and use cookies. By using this website, you accept these regulations. Our websites may contain links to websites of other providers to which this privacy policy does not extend."
      },
      {
        "type": "h3",
        "text": "Security"
      },
      {
        "type": "p",
        "text": "We use technical and organizational security measures to protect the data we have under our control against manipulation, loss, destruction and against access by unauthorized persons. Our security measures are continuously improved in line with technological developments."
      },
      {
        "type": "h3",
        "text": "Right to information, blocking and deletion"
      },
      {
        "type": "p",
        "text": "Upon request, we will inform you immediately in writing, in accordance with applicable law, whether and which of your personal data we have stored. If, despite our efforts to ensure that the data is correct and up to date, incorrect information has been stored, we will correct this at your request. You also have the right to have your personal data blocked or deleted at any time. If you have any questions regarding the processing of your personal data, you can contact our data protection officer, who is also available in the event of requests for information, suggestions or complaints. In addition, you have the right to lodge a complaint with a supervisory authority, in particular in the Member State of your residence, workplace or the place of the alleged infringement, if you believe that the processing of personal data concerning you is unlawful."
      },
      {
        "type": "h3",
        "text": "Responsible body"
      },
      {
        "type": "p",
        "text": "The responsible body within the meaning of the GDPR is:"
      },
      {
        "type": "p",
        "text": "Autak e.V."
      },
      {
        "type": "h3",
        "text": "Ottostr. 51A"
      },
      {
        "type": "h3",
        "text": "52070 Aachen"
      },
      {
        "type": "h3",
        "text": "Responsible supervisory authority"
      },
      {
        "type": "p",
        "text": "State Commissioner for Data Protection and Freedom of Information of North Rhine-Westphalia Postfach 20 04 44 40102 Düsseldorf Tel.: 0211/38424-0 Fax: 0211/38424-10 E-mail: poststelle@ldi.nrw.de"
      },
      {
        "type": "h3",
        "text": "Collection, processing and storage of personal data"
      },
      {
        "type": "p",
        "text": "When you visit our web pages, our web servers store by default the IP address assigned to you by your Internet service provider, the web page from which you visit us, the web pages you visit on our site, the browser type and version used, and the date and duration of your visit. With the exception of the IP address, personal data is only stored if and for the expressly stated purposes if you provide it to us of your own accord, e.g. as part of a registration, a survey, a competition or for the performance of a contract. Unless otherwise specified, personal data will only be stored by us for as long as is necessary to fulfill the purposes pursued."
      },
      {
        "type": "h3",
        "text": "Use, disclosure of personal data and purpose limitation"
      },
      {
        "type": "p",
        "text": "The legal basis for data processing in our association is Art 6 (1), letter f DSGVO. Our interests in data processing are in particular to ensure the operation of our association and the security of the website, to study the way visitors use the website, and to simplify the use of the website, as well as for marketing purposes to the extent necessary in each case. In particular, if you provide us with personal information for the purpose of informing you about our products and services, we would like to use your information to survey you as appropriate. Of course, participation in such campaigns is voluntary. If you do not agree to this, you can inform us at any time so that we can block the data accordingly. As a matter of principle, we do not pass on personal data without your consent. If and to the extent that we involve third parties in the performance of contracts (such as logistics service providers), they will only receive personal data to the extent that the transfer is necessary for the corresponding service. In the event that we outsource certain parts of data processing (\"commissioned processing\"), we contractually oblige commissioned processors to use personal data only in accordance with the requirements of data protection laws and to ensure the protection of the rights of the data subject. Transfers of personal data to governmental institutions and authorities only take place within the framework of mandatory national legal provisions. A data transfer to bodies or persons outside the EU outside the cases mentioned in this statement does not take place and is not planned. We reserve the right to check data retrospectively if concrete indications of illegal use become known or if it is necessary for the detection and elimination of malfunctions."
      }
    ]
  }
} as const satisfies Record<
  string,
  Record<string, readonly LegalBlock[]>
>;
