#!/usr/bin/env python3
"""One-off asset pipeline for the redesign.

Takes the raw one.com snapshot assets and produces web-ready output:

  * public/fonts      self-hosted Poppins + Comfortaa (latin subsets only),
                      extracted from the font cache the old PHP proxy left behind
  * public/images     resized/compressed photography derived from the
                      multi-megabyte camera originals in public/onewebmedia

Re-run with: python3 scripts/prepare-assets.py
"""

from __future__ import annotations

import os
import re
import shutil

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_CACHE = os.path.join(ROOT, "public", "onewebstatic", ".fonts-cache")
FONT_OUT = os.path.join(ROOT, "public", "fonts")
MEDIA_IN = os.path.join(ROOT, "public", "onewebmedia")
SHOP_IN = os.path.join(ROOT, "public", "webshopmedia")
IMAGE_OUT = os.path.join(ROOT, "public", "images")


def source_path(name: str) -> str | None:
    for folder in (MEDIA_IN, SHOP_IN):
        candidate = os.path.join(folder, name)
        if os.path.exists(candidate):
            return candidate
    return None

# Only latin coverage is needed for a German/English site; dropping devanagari,
# cyrillic, greek and vietnamese removes roughly two thirds of the font payload.
KEEP_SUBSETS = {"latin", "latin-ext"}
KEEP_WEIGHTS = {
    "Poppins": {"400", "500", "600", "700", "800"},
    "Comfortaa": {"400", "700"},
}

FACE_RE = re.compile(
    r"/\*\s*(?P<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?P<body>[^}]+)\}",
    re.MULTILINE,
)


def parse_faces(css: str):
    for match in FACE_RE.finditer(css):
        body = match.group("body")

        def field(name: str) -> str:
            found = re.search(rf"{name}:\s*([^;]+);", body)
            return found.group(1).strip() if found else ""

        url = re.search(r"url\(([^)]+)\)", body)
        if not url:
            continue

        yield {
            "subset": match.group("subset"),
            "family": field("font-family").strip("'\""),
            "style": field("font-style"),
            "weight": field("font-weight"),
            "range": field("unicode-range"),
            "url": url.group(1),
        }


def cached_woff2_for(url: str) -> str | None:
    """The proxy stored each file as md5(base64(originalUrl)).cache.woff2."""
    import base64
    import hashlib

    remote = re.sub(r"^.*\?url=", "", url)
    from urllib.parse import unquote

    remote = unquote(remote)
    digest = hashlib.md5(base64.b64encode(remote.encode())).hexdigest()
    path = os.path.join(FONT_CACHE, f"{digest}.cache.woff2")
    return path if os.path.exists(path) else None


def build_fonts() -> None:
    os.makedirs(FONT_OUT, exist_ok=True)
    seen: set[tuple[str, str, str, str]] = set()
    rules: list[str] = []

    for name in sorted(os.listdir(FONT_CACHE)):
        if not name.endswith(".cache.css"):
            continue

        with open(os.path.join(FONT_CACHE, name), encoding="utf-8") as handle:
            css = handle.read()

        for face in parse_faces(css):
            family = face["family"]
            if family not in KEEP_WEIGHTS:
                continue
            if face["subset"] not in KEEP_SUBSETS:
                continue
            if face["weight"] not in KEEP_WEIGHTS[family]:
                continue
            if face["style"] != "normal":
                continue

            key = (family, face["weight"], face["style"], face["subset"])
            if key in seen:
                continue

            source = cached_woff2_for(face["url"])
            if not source:
                continue

            seen.add(key)
            filename = f"{family.lower()}-{face['weight']}-{face['subset']}.woff2"
            shutil.copyfile(source, os.path.join(FONT_OUT, filename))

            rules.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                f"  font-style: {face['style']};\n"
                f"  font-weight: {face['weight']};\n"
                "  font-display: swap;\n"
                f"  src: url('/fonts/{filename}') format('woff2');\n"
                f"  unicode-range: {face['range']};\n"
                "}"
            )

    style_dir = os.path.join(ROOT, "src", "styles")
    os.makedirs(style_dir, exist_ok=True)
    out = os.path.join(style_dir, "fonts.css")
    header = "/* Generated by scripts/prepare-assets.py - do not edit by hand. */\n"
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(header + "\n".join(rules) + "\n")

    print(f"fonts: {len(seen)} faces -> {out}")


# source filename -> (output name, target width)
IMAGES = {
    "DSC07740.JPG": ("hero-aachen", 2400),
    "DSCF4581.JPG": ("pillars-banner", 1800),
    "PXL_20230327_113531680.PORTRAIT.jpg": ("wheelchair-prototype", 1800),
    "Autak_Prototyp.jpg": ("prototype-stairs", 1800),
    "DSC07616.JPG": ("connie-detail", 1600),
    "Team.JPG": ("team-workshop", 1800),
    "DSC03299.JPG": ("team-group", 1800),
    "DSC07923.JPG": ("community-event", 1600),
    "DSC07750.JPG": ("event-city", 1600),
    "Michael.jpg": ("portrait-michael", 1400),
}

# Gallery and project photography. Same pipeline as IMAGES, written to
# public/images/media so the editorial photos stay separate from the few
# curated hero shots above.
MEDIA = {
    "Autak - Bild 1.jpg": ("wheelchair-stairs", 1600),
    "Autak_Prototyp___serialized1.jpg": ("wheelchair-detail", 1600),
    "right_inclined_1.png": ("wheelchair-render", 1600),
    "1_Treppe.png": ("wheelchair-steps", 1600),
    "DSC07691-1653996206594.JPG": ("station-travel", 1600),
    "autak_kartenspiel_GC1-1654682879708.png": ("shop-card-game", 1200),
    "LunaLeg01-1676630708530.JPG": ("shop-lunaleg", 1200),
    "flat-seite-1695733946045.png": ("shop-flat", 1200),
    "20221006-0x5f-155715qu-1695733946045.jpg": ("shop-tag", 1200),
    "Kofferanhänger-Autak-2.png": ("aachen-crest", 1600),
    "IMG_0324.JPG": ("app-field-test", 1600),
    "Fahrplan.png": ("app-timetable", 1600),
    "Screenshot 2023-10-26 230536.png": ("supporters-strip", 1600),
    "20230426_151741.jpg": ("event-crowd", 1600),
    "Card_Game.jpg": ("shop-cards", 1600),
    "hannah-busing-Zyx1bK9mqmA-unsplash.jpg": ("learning-workshop", 1600),
    "camilo-jimenez-qZenO_gQ7QA-unsplash.jpg": ("event-lights", 1600),
    "LaserTag_4.JPG": ("event-lasertag", 1600),
    "DSC06588.JPG": ("event-panel", 1600),
    "DSC03330.JPG": ("accessibility-symbol", 1600),
    "DSC03358.JPG": ("portrait-outdoor-a", 1600),
    "DSC03401.JPG": ("portrait-desk", 1600),
    "DSC08098.JPG": ("demo-street", 1600),
    "PXL_20240504_143605176.MP.jpg": ("portrait-outdoor-b", 1600),
    "PXL_20240906_094349740.MP.jpg": ("booth-indoor", 1600),
    "PXL_20230915_134212285.MP.jpg": ("group-outdoor", 1600),
    "PXL_20220510_140036746.MP.jpg": ("wheelchair-event", 1600),
    "Laughing little girl sitting on the wheelchair at the hospital.jpg": (
        "user-portrait",
        1600,
    ),
    "shutterstock_265572854.jpg": ("navigation-city", 1600),
    "marianne-bos-eDOYvF6pM1I-unsplash.jpg": ("hands-map", 1600),
    "sebastian-hietsch-RUJYUXwj3s0-unsplash.jpg": ("stand-outdoor", 1600),
    "1280px-Aachen_Germany_Imperial-Cathedral-01.jpg": ("aachen-cathedral", 1600),
    "AutakVideoTdsI_1_Moment.jpg": ("video-poster-event", 1200),
    "ARD_Mediathek_Moment (1).jpg": ("video-poster-ard", 1200),
}

# Self-hosted clips. Copied to a clean path and given a poster frame, because
# the snapshot ships them under names full of spaces and no still image.
VIDEOS = {
    "titled Ppath.mp4": ("tilted-path", "00:00:02"),
    "Untitled video - Made with Clipchamp (2).mp4": ("stair-drive", "00:00:03"),
    "Untitled video - Made with Clipchamp (3).mp4": ("stair-climb", "00:00:03"),
    "Seating-Assembly_1_2024-Oct-16_01-52-38PM-000_CustomizedView6526314666_mp4.mp4": (
        "seat-assembly",
        "00:00:04",
    ),
}

# Portraits for the members page: square, small, one consistent size.
PORTRAITS = {
    "9_Gernot_Suemmermann.jpg": "gernot-suemmermann",
    "4-Manuel.png": "manuel-wessely",
    "9-Thomas.png": "thomas-hoenig",
    "Abhishek.jpg": "abhishek-ganesh",
    "6_Amol_Niranjan_Kodange.png": "amol-kodange",
    "3 (1).png": "nitish-aggarwal",
    "11.png": "leoni-kaever",
    "1.png": "niklas-degener",
    "2_Patricia_Fritze.png": "patricia-fritze",
    "8-Felix.png": "felix-reuter",
    "Subhangee.jpg": "subhangee-sahoo",
    "Aditi.jpg": "aditi-mishra",
    "5_Florian_Ernst.png": "florian-ernst",
    "11-Rene.png": "rene-rosenthal",
    "3-Niko.png": "nikolas-roessler",
    "Ece.jpg": "ece-angun",
    "5-Michael.png": "michael-heinrichs",
    "13-Julia.png": "julia-kampmann",
    "7.png": "simon-kumar",
    "10.png": "madlen-merklinger",
    "30-Chenyan.png": "chenyan-feng",
    "1-Juliane.png": "juliane-schlierkamp",
    "Neslihan.jpg": "neslihan-altinel",
    "6-Fiona.png": "fiona-hoenig",
    "10-Marcel.png": "marcel-wettlaufer",
    "8.png": "harshita-gupta",
    "28-Achim.png": "achim-kampker",
    "15-Mirco.png": "mirco-bolten",
    "17-Raul.png": "raul-krauthausen",
    "16-Mark.png": "mark-brandt",
    "27-Carsten.png": "carsten",
    "26-Tanja.png": "tanja-roembke",
    "20-David.png": "david-moser",
    "25-Horst.png": "horst-boltersdorf",
    "23-Kathy.png": "kathy-mulders",
    "29-Dennis.png": "dennis",
    "19-David.png": "david-lebhuser",
    "22-Lisa.png": "lisa-schmidt",
    "21-Zachi.png": "zacharias-wittmann",
    "18-Christian.png": "christian-bayerlein",
    "31-Lukas.png": "lukas-seidel",
    "24-Martin.png": "martin-westhoff",
}

PORTRAIT_SIZE = 480

LOGOS = {
    "Autak_Logo_white-NoSlogan.png": ("logo-white", 900),
    "Logo6.png": ("logo-mark", 512),
    "MDR_Logo_2017.svg.png": ("partner-mdr", 400),
    "CYBATHLON_Logo.png": ("partner-cybathlon", 400),
    "Logo_DigitalHub2.jpg": ("partner-digitalhub", 400),
    "FlukeLogo.png": ("partner-fluke", 400),
    "Kurtz-Ersa-Logo.png": ("partner-kurtzersa", 400),
    "ACE logo-01.png": ("partner-ace", 400),
    "Cambio_logo.svg.png": ("partner-cambio", 400),
    "low-tec-logo-top-300x156.png": ("partner-lowtec", 400),
}


def build_images() -> None:
    os.makedirs(IMAGE_OUT, exist_ok=True)

    for source, (stem, width) in IMAGES.items():
        path = os.path.join(MEDIA_IN, source)
        if not os.path.exists(path):
            print(f"  missing photo {source}")
            continue

        image = Image.open(path).convert("RGB")
        if image.width > width:
            height = round(image.height * width / image.width)
            image = image.resize((width, height), Image.LANCZOS)

        out = os.path.join(IMAGE_OUT, f"{stem}.jpg")
        image.save(out, "JPEG", quality=82, optimize=True, progressive=True)
        print(f"  {stem}.jpg {image.width}x{image.height} {os.path.getsize(out) // 1024}KB")

    media_out = os.path.join(IMAGE_OUT, "media")
    os.makedirs(media_out, exist_ok=True)

    for source, (stem, width) in MEDIA.items():
        path = source_path(source)
        if not path:
            print(f"  missing media {source}")
            continue

        image = Image.open(path).convert("RGB")
        if image.width > width:
            height = round(image.height * width / image.width)
            image = image.resize((width, height), Image.LANCZOS)

        out = os.path.join(media_out, f"{stem}.jpg")
        image.save(out, "JPEG", quality=80, optimize=True, progressive=True)
        print(f"  media/{stem}.jpg {image.width}x{image.height} {os.path.getsize(out) // 1024}KB")

    portrait_out = os.path.join(IMAGE_OUT, "people")
    os.makedirs(portrait_out, exist_ok=True)

    for source, stem in PORTRAITS.items():
        path = os.path.join(MEDIA_IN, source)
        if not os.path.exists(path):
            print(f"  missing portrait {source}")
            continue

        image = Image.open(path)
        # Cutouts are transparent PNGs; flatten onto the card background so the
        # portraits share one look with the photographic ones.
        if image.mode in ("RGBA", "LA", "P"):
            image = image.convert("RGBA")
            canvas = Image.new("RGBA", image.size, (240, 240, 240, 255))
            canvas.alpha_composite(image)
            image = canvas.convert("RGB")
        else:
            image = image.convert("RGB")

        side = min(image.width, image.height)
        left = (image.width - side) // 2
        image = image.crop((left, 0, left + side, side))
        image = image.resize((PORTRAIT_SIZE, PORTRAIT_SIZE), Image.LANCZOS)

        out = os.path.join(portrait_out, f"{stem}.jpg")
        image.save(out, "JPEG", quality=82, optimize=True, progressive=True)

    print(f"  portraits: {len(PORTRAITS)} -> {portrait_out}")

    build_videos(media_out)


def build_videos(poster_dir: str) -> None:
    """Copies the clips to /videos and grabs a poster frame with ffmpeg."""
    import subprocess

    video_out = os.path.join(ROOT, "public", "videos")
    os.makedirs(video_out, exist_ok=True)

    for source, (stem, timestamp) in VIDEOS.items():
        path = os.path.join(MEDIA_IN, source)
        if not os.path.exists(path):
            print(f"  missing video {source}")
            continue

        shutil.copyfile(path, os.path.join(video_out, f"{stem}.mp4"))

        poster = os.path.join(poster_dir, f"video-{stem}.jpg")
        result = subprocess.run(
            [
                "ffmpeg", "-y", "-loglevel", "error",
                "-ss", timestamp, "-i", path,
                "-frames:v", "1", "-vf", "scale=1200:-2", "-q:v", "4",
                poster,
            ],
            capture_output=True,
        )
        if result.returncode != 0:
            print(f"  poster failed for {stem}: {result.stderr.decode()[:120]}")
            continue

        print(f"  videos/{stem}.mp4 + poster")

    for source, (stem, width) in LOGOS.items():
        path = os.path.join(MEDIA_IN, source)
        if not os.path.exists(path):
            print(f"  missing logo {source}")
            continue

        image = Image.open(path).convert("RGBA")
        if image.width > width:
            height = round(image.height * width / image.width)
            image = image.resize((width, height), Image.LANCZOS)

        out = os.path.join(IMAGE_OUT, f"{stem}.png")
        image.save(out, "PNG", optimize=True)
        print(f"  {stem}.png {image.width}x{image.height} {os.path.getsize(out) // 1024}KB")


if __name__ == "__main__":
    build_fonts()
    print("images:")
    build_images()
